#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
python $SCRIPTPATH/pre-compile.py $@

HOST_PRESENT=false

for arg in $@; do
	if [[ $arg = "-DHOST"* ]]; then
		HOST_PRESENT=true
	fi
done

EXTRA_ARGS=()

if [ "$HOST_PRESENT" = false ]; then
	echo "USING DEFAULT HOST 127.0.0.1"
	EXTRA_ARGS=(-DHOST='"127.0.0.1"')
fi

arm-linux-gnueabi-gcc \
-fprofile-arcs \
-ftest-coverage \
-Wall \
-I$SCRIPTPATH \
$EXTRA_ARGS \
$@ \
-lpthread \
-lm

python $SCRIPTPATH/post-compile.py $@